### ISSUE TITLE
error 141

### ISSUE THREAD

**Issue by patidardhaval** [nodesocket/quote-stream#5]
working fine with less then 15 connection 
after 15 connection server stop with error events.js on 141

var PORT = 4000;
var FETCH_INTERVAL = 300;
var PRETTY_PRINT_JSON = true;

///
// START OF APPLICATION
///
var express = require('express');
var http = require('http');
var io = require('socket.io');

var app = express();
var server = http.createServer(app);
var io = io.listen(server);
io.set('log level', 1);

server.listen(PORT);

app.get('/', function(req, res) {
    res.sendfile(__dirname + '/index.html');
});

io.sockets.on('connection', function(socket) {
    socket.on('ticker', function(ticker) {
        track_ticker(socket, ticker);
    });
});

function track_ticker(socket, ticker) {
    //Run the first time immediately
    get_quote(socket, ticker);
    //Every N seconds
    var timer = setInterval(function() {
        get_quote(socket, ticker)
    }, FETCH_INTERVAL);
    socket.on('disconnect', function () {
        clearInterval(timer);
    });
}

function get_quote(p_socket, p_ticker) {

```
http.get({
    //host: 'www.google.com',
    host: 'localhost',
    port: 80,
    //path: '/webapp/info?client=ig&q=' + p_ticker
    path: '/webapp/user/bhavjson.php?check=0&Ses_id=' + p_ticker
}, function(response) {
    response.setEncoding('utf8');
    var data = "";

    response.on('data', function(chunk) {
        data += chunk;
    });

    response.on('end', function() {

        p_socket.emit('quote',data);

    });
});
```

}

**Comment by nodesocket** [comment]
Can you pull to latest `0.3.0`? Made major changes and refactors. If you still encounter problems, report back.
