### ISSUE TITLE
Connection refused after ~2 min

### ISSUE THREAD

**Issue by swimclan** [nodesocket/quote-stream#7]
After about 2 min of connectivity to the server, the express app is dumped with this exception:

```
Error: connect ETIMEDOUT 172.217.6.4:443
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
```

Do you think this could be Google dropping the connection?

**Comment by nodesocket** [comment]
Just tested with `http://localhost:4000/#AAPL` and worked for over 5 minutes for me. What ticker are you providing? Did you have multiple tabs open? Maybe you got rate limited?

**Comment by swimclan** [comment]
I used `AAPL` as well.  1 tab open.  Could be a rate limit.  Hard to tell.

**Comment by swimclan** [comment]
I ran it again and got ~6 min before it crashed.  Could be my ISP.  I will try on a server and see if I get better results.
